-- local autocmd = vim.api.nvim_create_autocmd
-- require("oil").setup()
-- Auto resize panes when resizing nvim window
-- autocmd("VimResized", {
--   pattern = "*",
--   command = "tabdo wincmd =",
-- })
-- vim.o.foldmethod = "expr"
-- vim.o.foldexpr   = "nvim_treesitter#foldexpr()"  -- UFO will override this; it just ensures expr‐mode is on
vim.g.python3_host_prog = '/usr/bin/python3'
-- vim.g.python2_host_prog = 'path/to/python2'
